name: CMake Build STM32 Project (gcc-arm-none-eabi)

# Because a PR results in a push; this workflow will run when a PR is merged
# or when a commit is pushed directly to any branch.
on:
  push:
    branches:
      - '*'
  pull_request:
    branches: [ "master" ]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install GCC ARM toolchain
        run: sudo apt-get update && sudo apt-get install -y gcc-arm-none-eabi

      - name: Configure CMake
        run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

      - name: Test
        working-directory: ${{github.workspace}}/build
        run: ctest -C ${{env.BUILD_TYPE}}
